source 'https://rubygems.org'

ruby '2.7.0'

gem 'sinatra',           '~> 2.1'
gem 'mongoid',           '~> 7.3'
gem 'jwt',               '~> 2.6'
gem 'bcrypt',            '~> 3.1'
gem 'rack-cors',         '~> 1.1'
gem 'mini_magick',       '~> 4.11'
gem 'streamio-ffmpeg',   '~> 3.0'
gem 'sidekiq',           '~> 6.5'
gem 'swagger-blocks',    '~> 3.0'
gem 'sinatra-namespace', '~> 1.3'
gem 'dotenv',            '~> 3.0'
gem 'rack-contrib',      '~> 2.0'  # for JSON body parser
